name: CI & Test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Test on Node v20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3

      - name: Setup Node.js environment 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Typecheck & ESLint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Build Docs
        run: pnpm build:docs

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@master
        with:
          branch: gh-pages
          node-version: 20.x
          folder: docs
