name: CI & Test

on:
  push:
    branches:
      - master
    paths:
      - src
      - test
      - package.json
      - .github/workflows/ci.yml

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Test on Node v22

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: PNPM setup
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Playwright
        run: pnpm exec playwright install

      - name: Typecheck & ESLint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Build Docs
        run: pnpm build:docs

      - name: ViTest
        run: pnpm test

      - name: Upload coverage report on to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          node-version: 20.x
          folder: docs
